version: "3.9"

services:
  backend:
    build: .
    container_name: mcq_backend
    restart: always
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "9001:9001"
    depends_on:
      - mongo
      - redis
    networks:
      - mcqnet

  mongo:
    image: mongo:7
    container_name: mcq_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mcqnet

  redis:
    image: redis:7-alpine
    container_name: mcq_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mcqnet

volumes:
  mongo_data:

networks:
  mcqnet:
